{% set version = "1.14.12" %}

package:
  name: cairo
  version: {{ version }}

source:
  url: http://cairographics.org/releases/cairo-{{ version }}.tar.xz
  sha256: 8c90f00c500b2299c0a323dd9beead2a00353752b2092ead558139bd67f7bf16

build:
  number: 4

requirements:
  build:
    - posix  # [win]
    - m2w64-xz  # [win]
    - pkg-config  # [not win]
    - libtool  # [not win]
    - xz  # [not win]
    - {{ compiler('c') }}
    - pthread-stubs  # [not win]
    - xcb-proto  # [not win]
    - xorg-renderproto  # [not win]
    - xorg-xproto  # [not win]
  host:
    - freetype  # [not win]
    - fontconfig  # [not win]
    - glib  # [not win]
    - icu
    - libpng
    - libxcb  # [not win]
    - pixman
    - xorg-libice  # [not win]
    - xorg-libsm  # [not win]
    - xorg-libx11  # [not win]
    - xorg-libxext  # [not win]
    - xorg-libxrender  # [not win]
    - zlib
  run:
    - freetype  # [not win]
    - fontconfig  # [not win]
    - glib  # [not win]
    - icu
    - libpng
    - libxcb  # [not win]
    - pixman
    - xorg-libice  # [not win]
    - xorg-libsm  # [not win]
    - xorg-libx11  # [not win]
    - xorg-libxext  # [not win]
    - xorg-libxrender  # [not win]
    - zlib

test:
  commands:
    # Check commands.
    - cairo-trace --help  # [not win]

    # Verify libraries.
    {% set cairo_libs = [
            "libcairo",
            "libcairo-gobject",
            "libcairo-script-interpreter",
    ] %}
    {% for each_cairo_lib in cairo_libs %}
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.a      # [not win]
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.so     # [linux]
    {% endfor %}

    # Check pkg-config files.
    - test -f $PREFIX/lib/pkgconfig/cairo-quartz.pc   # [osx]
    - test -f $PREFIX/lib/pkgconfig/cairo-xlib.pc     # [not win]

about:
  home: http://cairographics.org/
  license: LGPL 2.1 or MPL 1.1
  license_file: COPYING
  summary: 'Cairo is a 2D graphics library with support for multiple output devices.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
