{% set version = "1.8.10" %}

package:
  name: cairo
  version: {{ version }}

source:
  fn: cairo-{{ version }}.tar.xz
  url: http://cairographics.org/releases/cairo-{{ version }}.tar.gz
  sha1: 57fd2c7e0af16bee7cd53436d7c9dc526784f1da

build:
  number: 5
  skip: True  # [win and py>35]
  features:
    - vc9  # [win and py27]
    - vc10  # [win and py34]
    - vc14  # [win and py>=35]

requirements:
  build:
    - python  # [win]
    - posix  # [win]
    - m2w64-xz  # [win]
    - pkg-config  # [not win]
    - libtool  # [not win]
    - xz 5.2.*  # [not win]
    - freetype 2.7|2.7.*  # [not win]
    - fontconfig 2.12.*  # [not win]
    - glib 2.51.*  # [not win]
    - pixman 0.34.*
    - libpng >=1.6.28,<1.7
    - zlib 1.2.*
    - icu 58.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]
  run:
    - freetype 2.7|2.7.*  # [not win]
    - fontconfig 2.12.*  # [not win]
    - libpng >=1.6.28,<1.7
    - glib 2.51.*  # [not win]
    - pixman 0.34.*
    - zlib 1.2.*
    - icu 58.*
    - vc 9  # [win and py27]
    - vc 10  # [win and py34]
    - vc 14  # [win and py>=35]

test:
  commands:
    # Check commands.
    - cairo-trace --help  # [not win]

    # Verify libraries.
    {% set cairo_libs = [
            "libcairo",
            "libcairo-gobject",
            "libcairo-script-interpreter",
    ] %}
    {% for each_cairo_lib in cairo_libs %}
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.a      # [not win]
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.dylib  # [osx]
    - test -f $PREFIX/lib/{{ each_cairo_lib }}.so     # [linux]
    {% endfor %}
    - conda inspect linkages -p $PREFIX cairo  # [not win]
    - conda inspect objects -p $PREFIX cairo  # [osx]

about:
  home: http://cairographics.org/
  license: LGPL 2.1 or MPL 1.1
  summary: 'Cairo is a 2D graphics library with support for multiple output devices.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
