{% set version = "1.18.2" %}

package:
  name: cairo
  version: {{ version }}

source:
  url: http://cairographics.org/releases/cairo-{{ version }}.tar.xz
  sha256: a62b9bb42425e844cc3d6ddde043ff39dbabedd1542eba57a2eb79f85889d45a
  patches:
    - meson-darwin-versions.patch
    - windows-soversion-continuity.patch  # [win]

build:
  number: 1
  run_exports:
    - {{ pin_subpackage('cairo') }}

requirements:
  build:
    - m2w64-xz              # [win]
    - xz                    # [not win]
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - {{ compiler('cxx') }}
    - meson
    - ninja
    - pkg-config
    - pthread-stubs         # [linux]
    - xcb-proto             # [linux]
    - xorg-xorgproto        # [linux]
  host:
    - expat
    - freetype
    - fontconfig
    - glib
    - icu
    - libpng
    - libxcb                # [linux]
    - pixman
    - xorg-libice           # [linux]
    - xorg-libsm            # [linux]
    - xorg-libx11           # [linux]
    - xorg-libxext          # [linux]
    - xorg-libxrender       # [linux]
    - xorg-xorgproto        # [linux]
    - zlib

test:
  requires:
    - pkg-config
    # The packages are below are
    # needed for the pkg-config invocations below
    - expat
    - glib
    - zlib
    - xorg-xorgproto        # [linux]

  commands:
    # Check commands.
    - cairo-trace --help  # [not win]

    # Verify libraries. Note that on Windows, we patch Cairo's build system to
    # produce DLL names like `cairo.dll` rather than `cairo-2.dll` to maintain
    # continuity with binaries shipped before the switch to Meson.
    {% set cairo_libs = ["cairo", "cairo-gobject", "cairo-script-interpreter"] %}
    {% for each_cairo_lib in cairo_libs %}
    - test -f $PREFIX/lib/lib{{ each_cairo_lib }}.a                   # [not win]
    - test -f $PREFIX/lib/lib{{ each_cairo_lib }}.dylib               # [osx]
    - test -f $PREFIX/lib/lib{{ each_cairo_lib }}.so                  # [linux]
    - if not exist %LIBRARY_BIN%\{{ each_cairo_lib }}.dll exit /b 1   # [win]
    - if not exist %LIBRARY_LIB%\{{ each_cairo_lib }}.lib exit /b 1   # [win]
    - if not exist %LIBRARY_LIB%\{{ each_cairo_lib }}-static.lib exit /b 1  # [win]
    {% endfor %}

    # Check pkg-config files.
    - test -f $PREFIX/lib/pkgconfig/cairo-quartz.pc                  # [osx]
    - test -f $PREFIX/lib/pkgconfig/cairo-xlib.pc                    # [linux]
    - if not exist %LIBRARY_LIB%\pkgconfig\cairo-win32.pc exit /b 1  # [win]

    # check include files
    - test -f $PREFIX/include/cairo/cairo.h               # [unix]
    - if not exist %LIBRARY_INC%\cairo\cairo.h exit /b 1  # [win]

    # check that cairo was built with fontconfig support
    - grep -q "CAIRO_HAS_FC_FONT 1" $PREFIX/include/cairo/cairo-features.h  # [unix]

    - export PKG_CONFIG_PATH=$PREFIX/lib/pkgconfig   # [not win]
    - set "PKG_CONFIG_PATH=%LIBRARY_LIB%\pkgconfig"  # [win]
    - pkg-config --cflags cairo
    - pkg-config --cflags cairo-fc
    - pkg-config --cflags cairo-gobject

about:
  home: http://cairographics.org/
  dev_url: https://gitlab.freedesktop.org/cairo/cairo
  doc_url: https://www.cairographics.org/documentation/
  license: LGPL-2.1-only or MPL-1.1
  license_file:
    - COPYING
    - COPYING-LGPL-2.1
    - COPYING-MPL-1.1
  summary: 'Cairo is a 2D graphics library with support for multiple output devices.'

extra:
  recipe-maintainers:
    - ccordoba12
    - jakirkham
    - ocefpaf
    - pkgw
    - tschoonj
